# Generated by Django 4.0 on 2022-01-29 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdg', '0005_project_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
